project:
  type: book

execute:
  freeze: false

book:
  title: "Ciencia de datos con Julia"
  author: "Iraitz Montalbán"
  description: "Tutoriales y guías de ciencia de datos utilizando el lenguaje Julia."
  date: today
  cover-image: images/cover.png
  favicon: images/cover.png
  site-url: https://iraitzm.github.io/ciencia-datos-julia
  repo-url: https://github.com/IraitzM/ciencia-datos-julia
  page-navigation: true
  search: true
  sharing: [linkedin]
  sidebar:
    collapse-level: 1
    content: auto
    pinned: false
    style: docked
    background: light
  page-footer: 
    left: "Copyright 2025, Iraitz Montalbán" 
    right: 
      - icon: github
        href: https://github.com/IraitzM
      - icon: linkedin 
        href: https://www.linkedin.com/in/iraitzmontalban/
    border: false
    background: light
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Primeros pasos"
      chapters:
      - parts/firststeps/basics.qmd
      - parts/firststeps/flujos.md
      - parts/firststeps/librerias.qmd
      - parts/firststeps/sistemaficheros.qmd

    - part: "Carga y exploración"
      chapters:
      - parts/dataframes/basics.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    number-depth: 2
    theme: 
     - cosmo
     - style.scss
    code-link: true

# Some SEO
metadata:
  lang: es
  author: "Iraitz Montalbán"
  keywords: [Julia, Ciencia de Datos, Visualización, Machine Learning]
  twitter-card: false
  open-graph: true
  image: images/cover.png

google-analytics : "G-MXHDHE1HP5"

resources:
  - robots.txt



