# Prólogo {.unnumbered}

Este projecto lo inicio por haber querido emplear Julia en el ámbito profesional y no haber podido. Es mucho más habitual en mi entorno, por familiaridad y conveniencia, que los proyectos de ciencia de datos se realicen en otros lenguajes de programación. Sin embargo, quiero romper una lanza a favor de Julia como el lenguaje a emplear en ciencia de datos por su rendimiento y proximidad al dominio científico. Existen guía excepcionales en inglés:

* [Julia Data Science](https://juliadatascience.io/) [@storopolihuijzeralonso2021juliadatascience]
* [Julia for Data Science](https://www.juliafordatascience.com/)
* La documentación de [DataScienceTutorials.jl](https://juliaai.github.io/DataScienceTutorials.jl/)

Y algunas muy buenas referencias de programación en [Julia en Español](https://introajulia.org/latest/book.html).

Pero este es mi intento de acercarlo al público hispanohablante. Teniendo referencias en el idioma de uno es más fácil poder adoptar algo y crear una comunidad con contribuya tanto como lo hace la comunidad de Python.

Con suerte este libro ayuda a más de uno a perder el miedo y enfrentarse a este lenguaje que no deja de ser uno de los motivos por los que nuestros amados notebooks son notebooks de Jupyter (**Ju**lia, **pyt**hon y **R**).

## Sobre mí

Mi nombre es Iraitz Montalbán y llevo... algo de tiempo en esto de la ciencia de datos e inteligencia artificial. Puedes contactar directamente conmigo en [iraitz.info](https://iraitz.info/).

